# Generated by Django 4.2.11 on 2024-06-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_phone'),
        ('app', '0002_city_remove_client_address_client_city'),
    ]

    operations = [
    ]
